# Generated by Django 4.0.4 on 2022-07-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventsname', models.CharField(max_length=200, null=True)),
                ('choose_date', models.DateField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='facultyreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone_no', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200, null=True)),
                ('report', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone_no', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(null=True)),
                ('admission_no', models.CharField(max_length=200, null=True)),
                ('course', models.CharField(choices=[('BCA', 'BCA'), ('B.Voc', 'B.Voc'), ('MSc.Computer Science', 'MSc.Computer Science'), ('MSc.Data Analytics', 'MSc.Data Analytics')], default='NULL', max_length=200, null=True)),
                ('batch', models.CharField(choices=[('2020-2023', '2020-2023'), ('2019-2022', '2019-2022'), ('2018-2021', '2018-2021'), ('2017-2020', '2017-2020')], max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
